### PR TITLE
feat: Setup Bank Account Access module structure following Ledgers ar…

### LINKED ISSUE #2: Setup module structure for bank account access
**Description:**

In this ticket, we will define the basic structure for the Bank Account Access Management module, following the design principles and modular architecture used in the Ledgers . The module will handle account access control, providing roles and permissions for managing bank accounts. The goal is to establish a foundation for the development of repositories, services, entities, and REST APIs.

### PR DESCRIPTION
**Pull request by NkwaTambe**
**Setup Bank Account Access module structure following Ledgers architecture**
- Created base module `ledgers-bank-account-access` and base packages

### CODE REVIEW

**Review by Koufan-De-King — APPROVED** [review]
Nice!

**Review by nancymuyeh — APPROVED** [review]
Good to go :+1:

**Comment by Blindspot22** [comment]
@NkwaTambe sorry for reviewing this late.
But did you notice that this issue failed some tests??
Screenshot from 2024-09-25 15-27-57

Just wanted to ask if you checked them and you sure it won't lead to future conflicts!
Apart from that everything LGTM :rocket:

**Comment by NkwaTambe** [comment]
Yes @Blindspot22  nothing was working at first(0/6 checks failed) but after doing some fixes, we now have 4/6 check passed..

we are working as a team to fix the .yaml..

we need to move the project to java version 11 and so on...


To ensure that the .yaml workflows run before a pull request is merged (to avoid merging untested code), we need to modify our GitHub Actions workflow configuration to enforce running the checks on pull requests. By doing this, the workflow will be triggered as soon as a pull request is created, allowing for validation on the personal (feature) branch before merging it into the develop branch.

**Comment by Blindspot22** [comment]
> Yes @Blindspot22 nothing was working at first(0/6 checks failed) but after doing some fixes, we now have 4/6 check passed..
> 
> we are working as a team to fix the .yaml..
> 
> we need to move the project to java version 11 and so on...
> 
> To ensure that the .yaml workflows run before a pull request is merged (to avoid merging untested code), we need to modify our GitHub Actions workflow configuration to enforce running the checks on pull requests. By doing this, the workflow will be triggered as soon as a pull request is created, allowing for validation on the personal (feature) branch before merging it into the develop branch.

Great! Then i think an issue should be created for it specially with a concise description so as to make sure future updates could be done in referrence to it.

**Pull request merged**
